name: Build, Test & Publish

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1) Чекаутим код
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Устанавливаем .NET 8 SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3) Восстанавливаем зависимости
      - name: Restore solution
        run: dotnet restore CashCalculator.sln

      # 4) Сборка
      - name: Build solution
        run: dotnet build CashCalculator.sln --configuration Release --no-restore

      # 5) Тесты (если есть тестовый проект)
      - name: Run tests
        run: dotnet test .\CashCalculator.Tests\CashCalculator.Tests.csproj --configuration Release --no-build

      # 6) Публикация self-contained single-file
      - name: Publish single EXE
        run: |
          dotnet publish CashCalculator\CashCalculator.csproj \
            --configuration Release \
            --runtime win-x64 \
            --self-contained true \
            /p:PublishSingleFile=true \
            /p:EnableCompressionInSingleFile=true \
            --output publish

      # 7) Заливаем артефакт (exe и всё в папке publish)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CashCalculator-publish
          path: publish/