name: Build & Publish

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1) Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Install .NET 8 SDK
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3) Restore only the main project
      - name: Restore CashCalculator
        run: dotnet restore CashCalculator/CashCalculator.csproj

      # 4) Build in Release mode without re-restoring
      - name: Build CashCalculator
        run: dotnet build CashCalculator/CashCalculator.csproj --configuration Release --no-restore

      # 5) Publish as a single-file self-contained EXE
      - name: Publish single-file EXE
        run: dotnet publish CashCalculator/CashCalculator.csproj --configuration Release --runtime win-x64 --self-contained true /p:PublishSingleFile=true /p:EnableCompressionInSingleFile=true --output publish

      # 6) Upload the publish folder as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CashCalculator-publish
          path: publish/