name: Build & Publish

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Только основной проект
      - name: Restore CashCalculator
        run: dotnet restore CashCalculator/CashCalculator.csproj

      - name: Build CashCalculator
        run: dotnet build CashCalculator/CashCalculator.csproj \
          --configuration Release --no-restore

      # Тестов нет — этот шаг убран
      # - name: Run tests
      #   run: dotnet test ...

      - name: Publish single-file EXE
        run: |
          dotnet publish CashCalculator/CashCalculator.csproj \
            --configuration Release \
            --runtime win-x64 \
            --self-contained true \
            /p:PublishSingleFile=true \
            /p:EnableCompressionInSingleFile=true \
            --output publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CashCalculator
          path: publish/